[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    X-Frame-Options = "SAMEORIGIN"
    Feature-Policy = "microphone 'none'; geolocation 'none'"
    
